#!/bin/bash

User="$1"
File=/home/$User/.ssh/grabakey_id

if [ -f "$File" ]; then
    ID=`cat $File`
    curl https://grabakey.org/api/pubkey/$ID
    echo
fi

Dir=/home/$User/.ssh/grabakey_id.d

if [ -d "$Dir" ]; then
    for File in "$Dir/*"
    do
        ID=`cat $File`
        curl https://grabakey.org/api/pubkey/$ID
        echo
    done
fi
